Count down after asserting
SingleKeyGestureTests#testMultiPress occasionally fails (1% flake rate).
The failure message is like this:

java.lang.AssertionError: expected:<3> but was:<2>
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:647)
	at org.junit.Assert.assertEquals(Assert.java:633)
	at com.android.server.policy.SingleKeyGestureTests$1.onMultiPress(SingleKeyGestureTests.java:181)
	at com.android.server.policy.SingleKeyGestureTests$1.onKeyGesture(SingleKeyGestureTests.java:142)

Reviewing the code (and AI-suggested fixes), one potential way for this
to happen is for the .countDown() to fire before asserting, thus
allowing other (test) thread to proceed.

Currently the assertions are done in the handler thread, which is also
problematic (the test crashes whenever the assertion happens on non-test
thread).

One way to fix this is to avoid the "countdown" approach, and use a
queue-based mechanism, moving the assertions to the test thread.

However, since there is a large number of outstanding input bugs, this
change will not be pursued in this CL.

Bug: 485680425
Test: atest SingleKeyGestureTests#testMultiPress --rerun-until-failure 1000
Flag: EXEMPT TEST_ONLY
Change-Id: Ifb8f58fd8be052b8b9a92d4fbfbd653f300cb548