Make comparators in prop_info_cmp struct const
The clang toolchain update to r596125 causes the follwoing build
error:

prebuilts/clang/host/linux-x86/clang-r596125/include/c++/v1/__utility/lazy_synth_three_way_comparator.h:43:54: error: no matching function for call to object of type 'const (anonymous namespace)::prop_info_cmp'
   43 |   _LIBCPP_HIDE_FROM_ABI bool __less() const { return __comp_(__lhs_, __rhs_); }
      |                                                      ^~~~~~~
prebuilts/clang/host/linux-x86/clang-r596125/include/c++/v1/__tree:1802:20: note: in instantiation of member function 'std::__lazy_compare_result<(anonymous namespace)::prop_info_cmp, (anonymous namespace)::prop_info, (anonymous namespace)::prop_info>::__less' requested here
 1802 |     if (__comp_res.__less()) {
      |                    ^
prebuilts/clang/host/linux-x86/clang-r596125/include/c++/v1/__tree:942:38: note: in instantiation of function template specialization 'std::__tree<(anonymous namespace)::prop_info, (anonymous namespace)::prop_info_cmp, std::allocator<(anonymous namespace)::prop_info>>::__find_equal<(anonymous namespace)::prop_info>' requested here
  942 |           auto [__parent, __child] = __find_equal(__key);
      |                                      ^
prebuilts/clang/host/linux-x86/clang-r596125/include/c++/v1/set:729:20: note: in instantiation of function template specialization 'std::__tree<(anonymous namespace)::prop_info, (anonymous namespace)::prop_info_cmp, std::allocator<(anonymous namespace)::prop_info>>::__emplace_unique<const char *&, const char *&>' requested here
  729 |     return __tree_.__emplace_unique(std::forward<_Args>(__args)...);
      |                    ^
frameworks/base/ravenwood/runtime-jni/ravenwood_initializer.cpp:78:39: note: in instantiation of function template specialization 'std::set<(anonymous namespace)::prop_info, (anonymous namespace)::prop_info_cmp>::emplace<const char *&, const char *&>' requested here
   78 |     auto [it, success] = g_properties.emplace(key, value);
      |                                       ^
frameworks/base/ravenwood/runtime-jni/ravenwood_initializer.cpp:55:10: note: candidate function not viable: 'this' argument has type 'const (anonymous namespace)::prop_info_cmp', but method is not marked const
   55 |     bool operator()(const prop_info& lhs, const prop_info& rhs) {
      |          ^
frameworks/base/ravenwood/runtime-jni/ravenwood_initializer.cpp:61:10: note: candidate function not viable: 'this' argument has type 'const (anonymous namespace)::prop_info_cmp', but method is not marked const
   61 |     bool operator()(const prop_info& lhs, std::string_view rhs) {
      |          ^
frameworks/base/ravenwood/runtime-jni/ravenwood_initializer.cpp:58:10: note: candidate function not viable: 'this' argument has type 'const (anonymous namespace)::prop_info_cmp', but method is not marked const
   58 |     bool operator()(std::string_view lhs, const prop_info& rhs) {
      |          ^

This change heals the error and unblocks the toolchain update.

Bug: 472333761
Test: presubmit
Flag: EXEMPT PURE_REFACTOR
Change-Id: Ifa40950d7a596ffc2f15518d7613665f94e70d0d